apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: {{ .Values.rabbitmq.adminUser | b64enc | quote }}
  password: {{ .Values.rabbitmq.adminPassword | b64enc | quote }}
  erlangCookie: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}

