apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: amqp
  - port: {{ .Values.service.managementPort }}
    name: management
  selector:
    app: rabbitmq
  clusterIP: None

